#
# Copyright (c) 2021 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: catalog
spec:
  cluster: SockShop
  role: Catalog
  replicas: 1
  image: ghcr.io/oracle/coherence-spring-sockshop-catalog:1.5.2-SNAPSHOT
  env:
    - name: TRACING_HOST
      value: "jaeger-collector"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
    - name: COHERENCE_SERVICE_NAME
      value: "Catalog"
    - name: JAEGER_SERVICE_NAME
      value: catalog
    - name: JAEGER_ENDPOINT
      value: "http://jaeger-collector:14268/api/traces"
  application:
    main: com.oracle.coherence.examples.sockshop.spring.catalog.CatalogApp
    args:
      - "--port=8080"
      - "--management.tracing.enabled=false"
      - "--coherence.server.startup-timeout=5m"
  jvm:
    memory:
      heapSize: 2g
    args:
      - "-Dotel.java.global-autoconfigure.enabled=true"
      - "-Dotel.service.name=catalog"
      - "-Dotel.metrics.exporter=none"
      - "-Dotel.logs.exporter=none"
      - "-Dotel.exporter.otlp.traces.endpoint=http://jaeger-inmemory-instance-collector:4318/v1/traces"
      - "-Dotel.sdk.disabled=false"
      - "-Dcoherence.tracing.ratio=0"
  coherence:
    metrics:
      enabled: true
  ports:
    - name: http
      port: 8080
      service:
        name: catalogue  # for compatibility with the existing front-end implementation
        port: 80
      serviceMonitor:
        enabled: true
        path: /actuator/prometheus
    - name: metrics
      serviceMonitor:
        enabled: true
